In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-10-17 11:49:48.953938: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-10-17 11:49:48.955190: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-17 11:49:48.963179: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-10-17 11:49:48.982463: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-10-17 11:49:49.019057: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been 

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9511, 7069, 8848, 8011],
 [9511, 7069, 8848, 2530],
 [9511, 4160, 8848, 4006],
 [7188, 5870, 5227, 6969, 8822],
 [7188, 5870, 5227, 6969, 5716],
 [1102, 9511, 285, 8848, 4441],
 [9287, 6716, 8227, 6969]]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [30]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9511 7069 8848 8011]
 [   0    0    0    0 9511 7069 8848 2530]
 [   0    0    0    0 9511 4160 8848 4006]
 [   0    0    0 7188 5870 5227 6969 8822]
 [   0    0    0 7188 5870 5227 6969 5716]
 [   0    0    0 1102 9511  285 8848 4441]
 [   0    0    0    0 9287 6716 8227 6969]]


In [ ]:
## feature representation
dim=10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/suhas/.conda/envs/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [33]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step


array([[[-0.0157484 ,  0.0380298 ,  0.04151112, -0.02783616,
         -0.0211439 ,  0.02364277, -0.04717436,  0.03686502,
          0.01258805, -0.00790883],
        [-0.0157484 ,  0.0380298 ,  0.04151112, -0.02783616,
         -0.0211439 ,  0.02364277, -0.04717436,  0.03686502,
          0.01258805, -0.00790883],
        [-0.0157484 ,  0.0380298 ,  0.04151112, -0.02783616,
         -0.0211439 ,  0.02364277, -0.04717436,  0.03686502,
          0.01258805, -0.00790883],
        [-0.0157484 ,  0.0380298 ,  0.04151112, -0.02783616,
         -0.0211439 ,  0.02364277, -0.04717436,  0.03686502,
          0.01258805, -0.00790883],
        [-0.04313879,  0.00548631,  0.01956576,  0.04452587,
         -0.01169645, -0.01017629,  0.01203053,  0.02827145,
          0.01213719,  0.02333331],
        [ 0.02312112,  0.0088953 ,  0.02839441,  0.03191299,
         -0.04572323,  0.01071546,  0.04255902,  0.00530286,
         -0.01990603, -0.00336807],
        [ 0.00186927,  0.02044262, -0.01326127,  0.0

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 9511, 7069, 8848, 8011], dtype=int32)

In [36]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>